title: MMDV-Blockchain
url: https://luisromero78.github.io
baseurl: /MMDV-Blockchain   # ← nombre del repo, con mayúsculas si las tiene
theme: null                 # ← sin tema para que no vuelva Cayman

